### ISSUE TITLE
Selection is too dark

### ISSUE THREAD

**Issue by DmitriyD** [silvestreh/atom-material-syntax-dark#1]
Hello!

Really like this theme, but gray selection is barely visible on dark gray background.

**Comment by silvestreh** [comment]
Care to share a screenshot? Selection looks okay to me :confused:

**Comment by DmitriyD** [comment]
Something like this. Its really hard to see that all four `this` are selected even on my IPS monitor.

![Image](http://i.imgur.com/JcNsKKu.png)

**Comment by silvestreh** [comment]
Here's what they look like on my end (highlighted word is `color`):

![captura de pantalla 2015-12-27 a las 1 35 07](https://cloud.githubusercontent.com/assets/1133339/12008863/1db27b46-ac3a-11e5-8a50-992a0b61eae0.png)

BTW, I'm using the *development* version of Material UI which you are very much welcome to try. More info on that in the [Contributing section of the README file](https://github.com/silvestreh/atom-material-ui/blob/master/README.md#contributing).
