### ISSUE TITLE
Latest version not coloring code

### ISSUE THREAD

**Issue by matthewberkompas** [silvestreh/atom-material-syntax-dark#10]
I just updated to version 0.2.6 and my code is no longer being colored like it was before I updated (see example below). I'm not sure if this is something I did wrong or if it's an issue with the theme but you should know.
<img width="739" alt="screen shot 2017-01-14 at 1 46 00 pm" src="https://cloud.githubusercontent.com/assets/7084294/21958284/d43ea9f8-da5f-11e6-9bcb-0d97abae6446.png">

**Comment by silvestreh** [comment]
Did you upgrade to Atom 1.13?

**Comment by matthewberkompas** [comment]
I just did and it's working great. Thanks!

**Comment by silvestreh** [comment]
Cool, I'm rewriting the themes from scratch because the last automatic conversion didn't work out so good. Stay tuned for updates 😄

**Comment by matthewberkompas** [comment]
👍
