### ISSUE TITLE
every source like plain text

### ISSUE THREAD

**Issue by GabVenturato** [silvestreh/atom-material-syntax-dark#12]
Hi, with the last update (now I have 0.2.6 of this package and 1.3.9 of atom-material-ui), I see every source code like if it is plain text. i.e. every word is white with no highlight for every programming language.

I downloaded the 0.2.5.zip version and replaced all files inside "styles" folder with the older ones, and now it is everything like before: every programming language has its own syntax colors.

**Comment by silvestreh** [comment]
Did you upgrade to Atom 1.13?

**Comment by GabVenturato** [comment]
Sorry, my fault.
I have Fedora 24, with `dnf update` it says that everything is updated to the last available version, so I didn't check for a new version on the official website.

Now that you say it I checked what version of atom I have, and it says:

```
Name        : atom
Arch        : x86_64
Epoch       : 0
Version     : 1.11.2
Release     : 0.1
Size        : 235 M
Repo        : @System
From repo   : @commandline
Summary     : A hackable text editor for the 21st Century.
URL         : https://atom.io/
License     : MIT
Description : A hackable text editor for the 21st Century.
```

so I've cheked online and downloaded .rpm file from there, installed it, and now I have the 1.13.0 version. I don't know why fedora have the old one. Anyway thankyou for your help, maybe this can be useful for someone else who (like me) didn't check atom version from the official website.

**Comment by silvestreh** [comment]
I usually download and install Atom from [atom.io](http://atom.io) and it takes care of its own updates.

`1.13` deprecated most syntax CSS selectors so I updated the theme to match the new naming convention but I failed to make the update exclusive to the latest Atom version. I apologize for that.

I'm glad that you got it working though :)
