### ISSUE TITLE
Some issues with the new material syntax

### ISSUE THREAD

**Issue by pingshunhuangalex** [silvestreh/atom-material-syntax-dark#15]
Hi @silvestreh 
I've been using the new material syntax released last week, and many previous syntax highlighting issues did get fixed (like `margin.left` in js for example). However, it also introduce some other issues mostly in CSS/SCSS/Vue files

As pointed out in the below screenshot:
![image](https://cloud.githubusercontent.com/assets/17170199/26039098/9141b3b2-3959-11e7-9821-e3f8edacebfe.png)

1. The `style` tag will automatically lose its color as if the word color is preserved. It'll always give me this washed out color instead of the red ones as shown in the `script` tag you can see above it.

2. Very low contrast on descriptive attributes. Although the number and units looks good in yellow and orange, the descriptive attribute (text attribute) now looks a bit confusing as one uses cyan and the other uses teal which are quite similar.

3. The operators (`.`, `&`, `#`, etc.) used in CSS and SCSS are no longer highlighted (previously highlighted nicely in red) which are a bit annoying.

4. short hand CSS attribute like `font: 500 1.5rem sans-serif` for example, is not highlighted the same as the rest of the attributes (not in the screenshot).

Hope those issues can be fixed. Thanks.

**Comment by silvestreh** [comment]
This also happens with `material-syntax`

**Comment by pingshunhuangalex** [comment]
`undefined` in js (vue script part) is also not correctly highlighted.
![image](https://cloud.githubusercontent.com/assets/17170199/26105475/7104bbda-3a85-11e7-9faa-3438b9c51886.png)

**Comment by cbengtson85** [comment]
Also seeing a couple issues in javascript.
1. variable that were all caps were RED in the last version..now they are white
2. accessing props in objects  "action.response.results"  action is white and response and results are blue which looks weird.  last version was all white

**Comment by pingshunhuangalex** [comment]
Hi @silvestreh 
It's been a while now, just checking if this issue is still on your list. Thanks.

**Comment by silvestreh** [comment]
Hey, sorry for the lack of progress. I've been working a lot and spending time with my family during weekends. About to become a new dad, so, more than ever, I welcome pull requests 😄

**Comment by pingshunhuangalex** [comment]
@silvestreh No worries. Congratulations!!
