### ISSUE TITLE
0.2.6 breaking syntax highlighting

### ISSUE THREAD

**Issue by jdkschang** [silvestreh/atom-material-syntax-dark#9]
Updated to 0.2.6 and after restart doesn't highlight syntax for any of the extensions I'm using.

currently using:
* php
* javascript (Babel) ES2015
* s(css)

**Comment by jdkschang** [comment]
Resolved the issue by updating Atom

**Comment by silvestreh** [comment]
Yeah, sorry. That was my bad. I should've restricted the latest patch to Atom 1.13.0 users only.

**Comment by jdkschang** [comment]
@silvestreh No worries, wasn't hard to find and fix the issue; if anything, thanks for the inadvertent heads up on updating my atom version
